apiVersion: v1
kind: ServiceAccount
metadata:
  name: package-pipeline-sa
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: package-pipeline-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: package-pipeline-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: package-pipeline-sa
roleRef:
  kind: Role
  name: package-pipeline-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Pod
metadata:
  name: package-pipeline
  namespace: default
  labels:
    app: package-pipeline
spec:
  serviceAccountName: package-pipeline-sa
  containers:
  - name: pipeline
    image: ghcr.io/loshido/package-pipeline:latest
    env:
    - name: GITHUB_WEBHOOK_SECRET
      valueFrom:
        secretKeyRef:
          name: package-pipeling-secret
          key: webhook-secret

---

kind: Service
apiVersion: v1
metadata:
  name: package-pipeline-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: package-pipeline

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: package-pipeline-ingress
  namespace: default
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - '*.loshido.me'
        - loshido.me
      secretName: cloudflare-tls
  rules:
    - host: pipeline.loshido.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: package-pipeline-service
                port:
                  number: 80